name: cardly
description: A modern digital business card management app.
publish_to: 'none' # Remove this line if you plan to publish the package

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI & Fonts
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.9
  lottie: ^3.1.2

  # State Management
  provider: ^6.1.2

  # Networking & Storage
  http: ^1.2.2
  shared_preferences: ^2.3.2

  # Image & QR Code
  qr_flutter: ^4.1.0
  image_picker: ^1.1.2

  # Animations
  animations: ^2.0.11

  # Icons
  iconsax: ^0.0.8

  # Firebase (optional — enable later if needed)
  # firebase_core: ^3.5.0
  # firebase_auth: ^5.3.1
  # cloud_firestore: ^5.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
