// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJp_W4S3BaiV_dvG3g1qRoZAlSCqmKiW8',
    appId: '1:600083435846:web:6be1a1073de27ab5955547',
    messagingSenderId: '600083435846',
    projectId: 'cardly-db3b2',
    authDomain: 'cardly-db3b2.firebaseapp.com',
    storageBucket: 'cardly-db3b2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhFKio341IG-KfCl0ITfrLwCMTUry0vuI',
    appId: '1:600083435846:android:2d68ab76f8ea009a955547',
    messagingSenderId: '600083435846',
    projectId: 'cardly-db3b2',
    storageBucket: 'cardly-db3b2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkhRZYIgZDvhfk94Qr84HAA0mi2bUvRp0',
    appId: '1:600083435846:ios:5692f62a09ec0459955547',
    messagingSenderId: '600083435846',
    projectId: 'cardly-db3b2',
    storageBucket: 'cardly-db3b2.firebasestorage.app',
    iosBundleId: 'com.example.cardly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkhRZYIgZDvhfk94Qr84HAA0mi2bUvRp0',
    appId: '1:600083435846:ios:5692f62a09ec0459955547',
    messagingSenderId: '600083435846',
    projectId: 'cardly-db3b2',
    storageBucket: 'cardly-db3b2.firebasestorage.app',
    iosBundleId: 'com.example.cardly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJp_W4S3BaiV_dvG3g1qRoZAlSCqmKiW8',
    appId: '1:600083435846:web:660961a9378c55a6955547',
    messagingSenderId: '600083435846',
    projectId: 'cardly-db3b2',
    authDomain: 'cardly-db3b2.firebaseapp.com',
    storageBucket: 'cardly-db3b2.firebasestorage.app',
  );
}
